### ISSUE TITLE
`machine.reset_cause()` vs `Power.reset_cause()`

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/docs#2]
On https://docs.brilliantmonocle.com/micropython/micropython/#supported-modules

There is a Power.reset_cause().

Although, there seems to be something standard for micropython: https://docs.micropython.org/en/latest/library/machine.html?highlight=reset_cause#machine.reset_cause

Should it be kept or updated to `Power.reset_cause()` ?

**Comment by siliconwitch** [comment]
Yep. This was from Venkat's suggestion that reset and reset_cause is a power related function, hence it went into there. It's otherwise the same function

**Comment by josuah** [comment]
Thanks! Moving them then...
